#!/bin/bash

ENV_FILE="/srv/home-server/.env"
WIREGUARD_PORTAL_ADMIN_SERVICE_USER_PASSWORD=$(grep '^WIREGUARD_PORTAL_ADMIN_SERVICE_USER_PASSWORD=' "$ENV_FILE" | cut -d '=' -f2-)

echo $WIREGUARD_PORTAL_ADMIN_SERVICE_USER_PASSWORD