FROM debian:12-slim

# Install WireGuard and necessary tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wireguard-tools \
        wireguard-go \
        openresolv \
        iproute2 \
        iptables && \
        procps && \
    rm -rf /var/lib/apt/lists/*

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Start WireGuard
ENTRYPOINT ["/entrypoint.sh"]